/**
 * JWT Token Generator — Phase 4
 *
 * Generates one pre-signed HS256 JWT per role (admin, ops, branch).
 * Tokens are valid for 365 days from generation.
 *
 * Usage:
 *   npx ts-node scripts/generate-jwt.ts          # Print tokens to console
 *   npx ts-node scripts/generate-jwt.ts --write  # Also write to .env file
 *
 * Requires JWT_SECRET in .env. If missing, a random secret is generated.
 */

import "dotenv/config";
import crypto from "crypto";
import fs from "fs";
import path from "path";

// Re-implement inline to avoid import issues with ts-node path resolution
// (same implementation as src/lib/jwt.ts)

function base64urlEncode(data: string): string {
  return Buffer.from(data, "utf-8").toString("base64url");
}

interface JwtPayload {
  sub: string;
  role: string;
  iat: number;
  exp: number;
}

function signJwt(role: string, secret: string): string {
  const now = Math.floor(Date.now() / 1000);
  const payload: JwtPayload = {
    sub: "vehicle-stock-platform",
    role,
    iat: now,
    exp: now + 365 * 24 * 60 * 60, // 365 days
  };

  const header = { alg: "HS256", typ: "JWT" };
  const encodedHeader = base64urlEncode(JSON.stringify(header));
  const encodedPayload = base64urlEncode(JSON.stringify(payload));
  const signingInput = `${encodedHeader}.${encodedPayload}`;

  const signature = crypto
    .createHmac("sha256", secret)
    .update(signingInput)
    .digest("base64url");

  return `${signingInput}.${signature}`;
}

// ---- Main ----

const ROLES = ["admin", "ops", "branch"] as const;
const ENV_PATH = path.resolve(__dirname, "..", ".env");
const shouldWrite = process.argv.includes("--write");

function main() {
  // Get or generate JWT_SECRET
  let secret = process.env.JWT_SECRET;

  if (!secret || secret.trim().length === 0) {
    secret = crypto.randomBytes(64).toString("base64url");
    console.log("⚠️  JWT_SECRET not set in .env. Generated a random secret:");
    console.log(`   JWT_SECRET="${secret}"`);
    console.log("");
  }

  console.log("═══ JWT Tokens (Phase 4) ═══");
  console.log("Algorithm: HS256  |  Expiry: 365 days");
  console.log("");

  const tokens: Record<string, string> = {};

  for (const role of ROLES) {
    const token = signJwt(role, secret);
    tokens[role] = token;

    // Decode payload to show iat/exp
    const payloadPart = token.split(".")[1];
    const payload = JSON.parse(
      Buffer.from(payloadPart, "base64url").toString("utf-8"),
    );

    console.log(`── ${role.toUpperCase()} ──`);
    console.log(`Issued:  ${new Date(payload.iat * 1000).toISOString()}`);
    console.log(`Expires: ${new Date(payload.exp * 1000).toISOString()}`);
    console.log(`JWT:     ${token}`);
    console.log("");
  }

  // Write to .env if requested
  if (shouldWrite) {
    updateEnvFile(secret, tokens);
  } else {
    console.log("💡 Tip: run with --write to update .env automatically");
    console.log("   npx ts-node scripts/generate-jwt.ts --write");
  }
}

function updateEnvFile(secret: string, tokens: Record<string, string>) {
  let envContent: string;

  try {
    envContent = fs.readFileSync(ENV_PATH, "utf-8");
  } catch {
    envContent = "";
  }

  const lines = envContent.split("\n");
  const keysToReplace = ["JWT_SECRET", "JWT_ADMIN", "JWT_OPS", "JWT_BRANCH"];

  // Remove existing JWT lines
  const filtered = lines.filter(
    (line) =>
      !keysToReplace.some((key) =>
        line.trim().startsWith(`${key}=`),
      ),
  );

  // Remove trailing blank lines
  while (filtered.length > 0 && filtered[filtered.length - 1].trim() === "") {
    filtered.pop();
  }

  // Append JWT config
  filtered.push("");
  filtered.push("# JWT Auth — Phase 4 (generated by npm run jwt:generate)");
  filtered.push(`JWT_SECRET="${secret}"`);
  filtered.push(`JWT_ADMIN="${tokens.admin}"`);
  filtered.push(`JWT_OPS="${tokens.ops}"`);
  filtered.push(`JWT_BRANCH="${tokens.branch}"`);

  fs.writeFileSync(ENV_PATH, filtered.join("\n") + "\n");
  console.log(`✅ Updated ${ENV_PATH}`);
}

main();
